// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Ablums: typeof import('./src/components/ablums/ablums.vue')['default']
    Cellphone: typeof import('./src/components/cellphone/cellphone.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    Email: typeof import('./src/components/eamil/email.vue')['default']
    Follow: typeof import('./src/components/follows/follow.vue')['default']
    Followed: typeof import('./src/components/followed/followed.vue')['default']
    Follows: typeof import('./src/components/follows/follows.vue')['default']
    Likemusci: typeof import('./src/components/like/likemusci.vue')['default']
    Likemusic: typeof import('./src/components/like/likemusic.vue')['default']
    Login: typeof import('./src/components/account/login.vue')['default']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    Musiclist: typeof import('./src/components/musiclist/musiclist.vue')['default']
    Musics: typeof import('./src/components/musics/musics.vue')['default']
    Mv: typeof import('./src/components/mv/mv.vue')['default']
    Newablum: typeof import('./src/components/home/newablum.vue')['default']
    Nmheader: typeof import('./src/components/navigation/Nmheader.vue')['default']
    Play: typeof import('./src/components/btmplay/play.vue')['default']
    Playmusic: typeof import('./src/components/play/playmusic.vue')['default']
    Playmv: typeof import('./src/components/mv/playmv.vue')['default']
    Pm: typeof import('./src/components/btmplay/pm.vue')['default']
    Qrcode: typeof import('./src/components/qrcode/qrcode.vue')['default']
    Ranking: typeof import('./src/components/ranking/ranking.vue')['default']
    Rec: typeof import('./src/components/home/rec.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Singers: typeof import('./src/components/ablums/singers.vue')['default']
    Song: typeof import('./src/components/songlist/song.vue')['default']
    Way: typeof import('./src/components/loginWayChoose/way.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
