// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cellphone: typeof import('./src/components/cellphone/cellphone.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Email: typeof import('./src/components/eamilLogin/email.vue')['default']
    Login: typeof import('./src/components/accountPage/login.vue')['default']
    Nmheader: typeof import('./src/components/head_navigation/Nmheader.vue')['default']
    Qrcode: typeof import('./src/components/loginByQRcode/qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
